apiVersion: v1
kind: Pod
metadata:
  name: configuration-po
spec:
  containers:
    - image: wurstmeister/zookeeper
      name: zookeeper
    - image: wurstmeister/kafka
      name: kafka
      env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: localhost
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: localhost:2181
      ports:
        - containerPort: 9092
          name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app-name: configuration-server
  template:
    metadata:
      labels:
        app-name: configuration-server
    spec:
      containers:
        - name: configuration-server
          image: wiewioor222/configuration_server_training
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: configuration-map


---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  type: LoadBalancer
  selector:
    app-name: configuration-po
  ports:
    - port: 9092
      targetPort: kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-map
data:
  KAFKA_SERVER: 'configuration-service'
  KAFKA_PORT: '9092'
  SLEEP_TIME: '1'
  DEFAULT_PROFILE: 'production'
  
